### ISSUE TITLE
Writing effective tests?

### ISSUE THREAD

**Issue by utsengar** [alexandru/scala-best-practices#23]
What do you suggest about writing effective and quick unit tests?
Your suggestion about not to use cake pattern (or any DI technique) basically helps us abstract things so that code can be isolated and tested by mocking its dependencies.

Lets take an example of a Play controller.

We need to dependencies to build a controller: "Service" and "Repository" where service handles the business logic and deals only with domain objects. The repository talks to the DB. The controller talks to the services, converts the domain object to json, xml, html etc.

Now, if I need to test only the service, I need to mock the repository which has a defined interface. How do you suggest that should be dealt with?

Testing controller can be an integration test but service tests about be unit tests and should take <4 seconds to complete.

I am coming from a background of constructor injection (http://misko.hevery.com/2009/02/19/constructor-injection-vs-setter-injection) and trying to implement the credit card processor example the scala way.

**Comment by alexandru** [comment]
> Now, if I need to test only the service, I need to mock the repository which has a defined interface. How do you suggest that should be dealt with?

Care to give an example of what you mean?

In my experience, you don't need dependency injection to mock things. And note that I do not consider "*constructor injection*" to be "*dependency injection*". In my view ...

1. all dependencies should be specified as constructor or function parameters (implicits included, but with great care)
2. if it's beginning to hurt (i.e. too many dependencies, or dependencies that contain things you don't need), well, that's because the code in question sucks and needs to be refactored - hurt is a very beneficial effect that is hidden by dependency injection frameworks or the Cake Pattern

And the need to mock is largely overrated - meaning that there are many cases in which the wiring between components can be very loose, so you don't need to mock with careful design. But we are talking in the abstract here and this isn't very useful, so expand on your examples (give me some interface for Service / Repository).

Also note that I'm not an expert on unit-testing, I only have some experience and some ideas, therefore I abstained from developing the subject further. But lets talk.

**Comment by utkarsh2012** [comment]
I am coming from a java background and been tinkering with scala from the last 2 weeks.

This is how I would have implemented a credit card processor in java (from the example in the link above):

    Database db = new MySQLDatabase("username", "password", "jdbc:....");
    OfflineQueue queue = new RedisOfflineQueue(db);
    CreditCardProcessor processor = new StripeCreditCardProcessor(queue, db);
    processor.charge(.....)

Where 
1. Database is an interface and MySQLDatabase is its implementation.
2. OfflineQueue is an interface and RedisOfflineQueue is its implementation.

Now, when I need to test `processor.charge`, I will simply mock `Database` class with `MockDatabase` whose `insert` returns a success. In the same way, I will mock `OfflineQueue` with `MockOfflineQueue` if its being used by `CreditCardProcessor`.

Its a standard way of making your code testable without doing DI in the java world.

How would you write your scala code when you needed to achieve something similar?

**Comment by alexandru** [comment]
Hey @utkarsh2012, I've forgotten about your question :-)

In my opinion this isn't a Java vs Scala thing, but rather a general question of design. If you have code like that, by all means, you can use mocking, however I sometimes prefer to take a step back and think about how to completely decouple these things.

It really depends on what your use-case is and what you want to test, but many times what happens is that some component `CA` in response to some event `EA` will call into the implementation of component `CB` as a side-effect of event `EA` to do things, such as saving something into the database, or send an event over RabbitMQ, etc..., lets call it event `EB`, an action that isn't essential to the business logic inside of component `CA` that you want to test, your only care being to see that action being triggered and that's it. And this does create a need for mocking component `CB`.

But, what if you'd use the [observer pattern](https://en.wikipedia.org/wiki/Observer_pattern)?

What if component `CB` would subscribe to component's `CA`'s events. Component `CA` in response to event `EA` would emit an event `EB` that eventually `CB` will receive and process. So for example, do you really, really need that RabbitMQ interface in your component, when your component could simply expose an *observable* source of events? And there are many instances in which your components shouldn't care about what happens as side-effects of certain actions. I'm a little biased btw - these days my applications are a combination of Akka actors that aren't tightly coupled, evolving immutable data-structures, combined with Rx observables that trigger side-effecting events.

Anyway, I don't really care about the ability to mock or dependency injection, all I care about is that the cake pattern has been a failed experiment and it saddens me to see it used so often :-)

**Comment by jimschubert** [comment]
I think this is actually a good question. When I last used Scala a few years ago, the cake pattern was the _de facto_ pattern for writing testable code. There are other approaches that aren't necessarily Scala-specific like factory/builder pattern or DI frameworks like Google's guice. But in Scala, you can also use structural types to write testable code. 

[This is a great article on the subject](http://www.codeproject.com/Articles/1057967/Scala-Dependency-Injection-IoC).

I think a community defined best practice would be useful.

**Comment by rahul04091987** [comment]
I am also from java baground and currently developing an Rest app with play Scala .I have done mocking for service but what about dao .Each dao repository has a Table and a DBconfugrationprpvoder .How to mock Table class in this case
