### ISSUE TITLE
IMPORTANT: Rewriting history of repository

### ISSUE THREAD

**Issue by alexandru** [alexandru/scala-best-practices#35]
This is of special interest to @Peranikov, @piruty-joy, seeing that they are working on a Japanese translation. And for anybody else with active forks.

I've rewritten the whole history of the project to hide my emails behind `noreply@alexn.org`. This is because GitHub has become a spam problem for me and I do not want to expose my real emails anymore. I've followed the tutorial here and have only touched my own commits: https://help.github.com/articles/changing-author-info/

Existing forks have to rebase off the new master, otherwise your branch is going to be divergent. The recipe for doing that goes something like this:

1. BACKUP
2. DO NOT start with a `git pull`
3. `git fetch`
4. `git rebase --onto origin/master master <local_branch>` (for local each branch)
5. `git pull --force`

Sorry for the inconvenience and let me know if you need help.

**Comment by Peranikov** [comment]
Hi @alexandru.

Thank you for your message. I updated my fork repository.
Please your continuous support.

sincerely,

Peranikov

**Comment by alexandru** [comment]
I'm closing this.
