### ISSUE TITLE
Update rule 2.11 to discourage use of joda-time in favour of java.time

### ISSUE THREAD

**Issue by jjst** [alexandru/scala-best-practices#44]
Rule 2.11 states:

> 2.11. MUST NOT use Java's Date or Calendar, instead use Joda-Time or JSR-310

JSR-310 has now been implemented as [Java 8's new java.time API](http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html) and [even jodatime's website is asking users to migrate](http://www.joda.org/joda-time/).
As Java 8 has become more and more common, it's probably time to deemphasise joda-time and recommend the java.time API as the standard approach, with joda-time as a fallback for people stuck in pre-Java 8 land.

**Comment by frgomes** [comment]
indeed! +1

**Comment by alexandru** [comment]
Sure. Any of you up for a PR?

**Comment by jjst** [comment]
Sure :)
