### ISSUE TITLE
Reference to JMH, Scala Meter

### ISSUE THREAD

**Issue by satybald** [alexandru/scala-best-practices#48]
While highly agree that [benchmarking is hard](https://github.com/alexandru/scala-best-practices/blob/master/sections/3-architecture.md#33-should-not-apply-optimizations-without-profiling) and proper tools need to be used. I have some question regarding a reference to Google Calibre. I don't want to open flame war but would it be better to reference a JMH and Scala Meter projects here?

Google Calibre vs JMH discussion:
https://groups.google.com/forum/#!msg/mechanical-sympathy/m4opvy4xq3U/7lY8x8SvHgwJ

**Comment by alexandru** [comment]
I personally use JMH and not Google Calibre. If you want, submit a pull request.

**Comment by satybald** [comment]
yup, I'll do it. I'll also add a reference to Scala Meter project.
