### ISSUE TITLE
Add a rule: case classes SHOULD be final

### ISSUE THREAD

**Issue by jordanobodh** [alexandru/scala-best-practices#55]
As extending a `case class` would lead to unexpected behaviour, a rule should be added that case classes should be final.
[Why case classes should be final](https://stackoverflow.com/questions/34561614/should-i-use-the-final-modifier-when-declaring-case-classes)

**Comment by speedcom** [comment]
Why case classes are not "final by default in Scala?

**Comment by alexandru** [comment]
There are certain instances in which you want to override the methods of a case class.

Very rare. And it's not worth it. They should have been final.

**Comment by alexandru** [comment]
If anybody wants to add the rule, I'll merge it.

**Comment by kusumakarb** [comment]
I'll submit the PR.
